### ISSUE TITLE
Sharelatex and Overleaf will be merged

### ISSUE THREAD

**Issue by CptPie** [fs-wiai/LaTeX-Tutorial#1]
A few months (20.07.2017) ago both companies announced that they will merge their services (https://www.sharelatex.com/blog/2017/07/20/sharelatex-joins-overleaf.html)

Issue at einfuehrung.tex (line 181-184)

**Comment by muellermartin** [comment]
Thanks for this information! We will adjust our presentation accordingly :)

**Comment by LinusDietz** [comment]
@muellermartin, @CptPie done
