### ISSUE TITLE
Notable mention for LaTeX Editors

### ISSUE THREAD

**Issue by CptPie** [fs-wiai/LaTeX-Tutorial#4]
One editor you could mention would be Gummi (https://github.com/alexandervdm/gummi)
Fully opensource, full support for any Linux distribution, beta version for windows, live compiling, handy feature for custom code completion

**Comment by muellermartin** [comment]
As you can probably see in [line 130 of file /Deutsch/beamer/content/einfuehrung.tex](https://github.com/fs-wiai/LaTeX-Tutorial/blob/e570c67a5a0917e38d17c73505deca039703358a/Deutsch/beamer/content/einfuehrung.tex#L130) we had some more editors mentioned, but we commented them out to keep the presentation clean and to not confuse newcomers.

**Comment by muellermartin** [comment]
I'm closing this as the suggested editor is very platform-specific and we already have alternatives listed. I'd rather include tools like TeXworks as it supports major platforms and is similarly "simple" and mention that every plaintext editor should suffice.
