### ISSUE TITLE
Improvements chapter 'Grafiken'

### ISSUE THREAD

**Issue by CptPie** [fs-wiai/LaTeX-Tutorial#5]
It might just be my personal opinion but i have often seen \centering instead of the center environment which works in the same way

**Comment by CptPie** [comment]
Also using the H modifier for float positioning is considered bad practice.
Just saying :D

**Comment by agp8x** [comment]
There are subtle differences how \centering and the center environment work (mainly vertical spacing}. So when centering e.g. a figure, centering might be a better choice. However, I could not find any usage of \centering during the presentation, just some of the template files provided use it.
