### ISSUE TITLE
How to avoid section headings overwriting the margin in the header

### ISSUE THREAD

**Issue by L0g4n** [fs-wiai/LaTeX-Tutorial#7]
I am using this theme for a presentation and all the section titles are listed in the header of each frame.

Now I am facing the problem that I have so many / lenghty sections that the header of section overwrites the margin and LaTex does NOT insert a line break to avoid this.

In your presentation this is not the case and the section titles are correctly wrapped in a newline. How can i realize this behaviour? I already looked in your beamer code but did not find it yet.

**Comment by muellermartin** [comment]
Nice to hear that this project is used. Could you provide a minimal working example with a screenshot to make reproduction of this issue easier for us?

**Comment by L0g4n** [comment]
<img width="552" alt="overwriting_margin" src="https://user-images.githubusercontent.com/7620524/59356594-70f83100-8d29-11e9-80e2-ae2508926119.png">

See the above picture for the concrete problem.

Minimal working example:
My `commands.tex` file which is included by the main presentation file:
`
\documentclass[11pt, english]{beamer}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[english]{babel}
\usepackage{lmodern}

\usepackage{graphicx,booktabs,float}
\usepackage{color}
% config here bibliography style
\usepackage{natbib}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{caption}

\usepackage{multicol, multirow}

\usepackage{subfig}
\usepackage{hyperref}
%\usepackage{cleveref}

\usepackage{ulem}
\usepackage{stmaryrd}
\usepackage{url}

\usetheme{UniBa}
\usefonttheme{professionalfonts}
\useinnertheme{rectangles}
\setbeamercovered{transparent}
% Without navigation symbols
\beamertemplatenavigationsymbolsempty

\newcommand{\unibastring}{University of Bamberg}
`


`main.tex` file which includes the content files:
`
% Main file
\input{config/commands.tex}

% to get numbered figures
\setbeamertemplate{caption}[numbered]

\begin{document}

% meta information, here OMITTED
\author{}
\title{}
\subtitle{}
\date{}
\institute{}

\begin{frame}
    \titlepage
\end{frame}

\begin{frame}
    \frametitle{Outline}
    \tableofcontents[]
\end{frame}

%\begin{frame}\end{frame} % to enforce entries in the table of contents

% Content begins HERE
% TODO: add content input files
\input{content/motivation.tex}
% and so on

% ---- Bibliography ----
%\bibliographystyle{config/splncsnat}
%\bibliography{literature/bibtex}
\section*{}
\begin{frame}[allowframebreaks]{References}
\def\newblock{\hskip .11em plus .33em minus .07em}
\scriptsize
\bibliographystyle{config/splncsnat}
\bibliography{literature/bibtex}
\normalsize
\end{frame}
\end{document}
`

**Comment by muellermartin** [comment]
Ah, thanks for providing an example. We did not solve this automatically. We deliberately used short section names so they fit into the header, e.g. see [/Deutsch/beamer/content/distributed.tex in line 1](https://github.com/fs-wiai/LaTeX-Tutorial/blob/f34538d44d6e81e6527695cbf8a5d32771058d27/Deutsch/beamer/content/distributed.tex#L1): `\section{Vert. Arbeiten}`

A sligtly (but still not automated solution) would be to use a shorter version of the section title in brackets, see: https://tex.stackexchange.com/a/22405

If this answer solves the issue for you, feel free to close this issue.

**Comment by L0g4n** [comment]
Thanks, I solved in via the shorter version of the section title in the end.
