### ISSUE TITLE
Englische Version der Abschlussarbeit Vorlage

### ISSUE THREAD

**Issue by L0g4n** [fs-wiai/LaTeX-Tutorial#8]
Hi,

die Frage bezieht sich nicht direkt auf die Beamer Folien, aber da ich im VC Kurs gesehen habe, dass es einen deutsches Template für Abschlussarbeiten gibt, gibt es auch direkt irgendwo eine englische Version (im VC ist ja nur die deutsche zum DL)? Wenn nicht, ist das auch nicht schlimmt, ich will bloß nicht alles zu englischen Titeln abändern, wenn es das von euch schon fertig gibt.

**Comment by mtraeger** [comment]
Hi, 
die Lehrstühle bieten häufig selbst ihre Vorgaben auf Englisch an. Falls nicht, gäbe es hier eine Vorlage:
https://github.com/christian-steinmeyer/theses-template

Falls nötig auch mit angepassten Image-Befehlen: https://github.com/mtraeger/theses-template/tree/addAndFixImageCommands

**Comment by L0g4n** [comment]
Hi,

danke für den Link, ja ich habe bereits beim SME Lehrstul gefragt, der Prof. hat mir aber gesagt, dass sie keine haben und ich mal bei der Fachschaft fragen soll.
